ADDONS = "/addons"
CHARACTERS = "/character"
ITEMS = "/item"
OFFERINGS = "/offering"
PERKS = "/perks"
STATUSES = "/status"
PLAYERS = "/players"
DBD_VERSION = "/dbd-version"
MATCHES = "/matches"
LABELS = "/labels"

CROP = "/crop"
PREDICT = "/predict"
BACKUP = "/backup"
