ADDONS = "/addons"
CHARACTERS = "/characters"
ITEMS = "/items"
OFFERINGS = "/offerings"
PERKS = "/perks"
STATUSES = "/statuses"
PLAYERS = "/players"
DBD_VERSION = "/dbd-version"
MATCHES = "/matches"
LABELS = "/labels"

CROP = "/crop"
PREDICT = "/predict"
BACKUP = "/backup"
